baseURL = "kubespaces.io"
themesDir = "themes"
theme = "hugo-hero-theme"
languageCode = "en-us"
title = "Kubespaces.io"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id="G-HX5KLVX6TG"

  [params.logo]
    mobile = "images/kubespaces2.png"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/kubespaces2.png"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Kubespaces"

  [params.homepage_meta_tags]
    meta_description = "Kubespaces is namespaces-as-a-service for your organization"
    meta_og_title = "Kubespaces"
    meta_og_type = "website"
    meta_og_url = "https://kubespaces.io"
    meta_og_image = ""
    meta_og_description = "Kubespaces is namespaces-as-a-service for your organization"
    meta_twitter_card = "summary"
    meta_twitter_site = "@kubespaces"
    meta_twitter_creator = "@kubespaces"

#[[menu.main]]
#	name = "Services"
#	url = "/services/"
#    weight = 1

#[[menu.main]]
#    name = "Work"
#    url = "/work/"
#    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
